<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="2" failed="2" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-05-20T20:13:49 IST" name="Suite" finished-at="2023-05-20T20:14:27 IST" duration-ms="38175">
    <groups>
      <group name="ErrorHandling">
        <method signature="ErrorValidationsTest.LoginErrorValidation()[pri:0, instance:SeleniumFrameworkDesign.tests.ErrorValidationsTest@4b6690c0]" name="LoginErrorValidation" class="SeleniumFrameworkDesign.tests.ErrorValidationsTest"/>
      </group> <!-- ErrorHandling -->
      <group name="Purchase">
        <method signature="SubmitOrderTest.submitOrder(java.util.HashMap)[pri:0, instance:SeleniumFrameworkDesign.tests.SubmitOrderTest@294a6b8e]" name="submitOrder" class="SeleniumFrameworkDesign.tests.SubmitOrderTest"/>
      </group> <!-- Purchase -->
    </groups>
    <test started-at="2023-05-20T20:13:49 IST" name="Error validation Test" finished-at="2023-05-20T20:14:13 IST" duration-ms="23497">
      <class name="SeleniumFrameworkDesign.tests.ErrorValidationsTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:SeleniumFrameworkDesign.tests.ErrorValidationsTest@4b6690c0]" started-at="2023-05-20T20:13:49 IST" name="launchApplication" finished-at="2023-05-20T20:13:55 IST" duration-ms="6019" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="LoginErrorValidation()[pri:0, instance:SeleniumFrameworkDesign.tests.ErrorValidationsTest@4b6690c0]" started-at="2023-05-20T20:13:55 IST" name="LoginErrorValidation" finished-at="2023-05-20T20:13:57 IST" duration-ms="1391" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:SeleniumFrameworkDesign.tests.ErrorValidationsTest@4b6690c0]" started-at="2023-05-20T20:13:57 IST" name="tearDown" finished-at="2023-05-20T20:13:57 IST" duration-ms="101" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:SeleniumFrameworkDesign.tests.ErrorValidationsTest@4b6690c0]" started-at="2023-05-20T20:13:57 IST" name="launchApplication" finished-at="2023-05-20T20:13:58 IST" duration-ms="1598" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="ProductErrorValidation()[pri:0, instance:SeleniumFrameworkDesign.tests.ErrorValidationsTest@4b6690c0]" started-at="2023-05-20T20:13:58 IST" name="ProductErrorValidation" finished-at="2023-05-20T20:14:12 IST" duration-ms="13951" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at SeleniumFrameworkDesign.tests.ErrorValidationsTest.ProductErrorValidation(ErrorValidationsTest.java:54)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ProductErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:SeleniumFrameworkDesign.tests.ErrorValidationsTest@4b6690c0]" started-at="2023-05-20T20:14:13 IST" name="tearDown" finished-at="2023-05-20T20:14:13 IST" duration-ms="109" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- SeleniumFrameworkDesign.tests.ErrorValidationsTest -->
    </test> <!-- Error validation Test -->
    <test started-at="2023-05-20T20:13:49 IST" name="Submit Order Test" finished-at="2023-05-20T20:14:27 IST" duration-ms="38175">
      <class name="SeleniumFrameworkDesign.tests.SubmitOrderTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:SeleniumFrameworkDesign.tests.SubmitOrderTest@294a6b8e]" started-at="2023-05-20T20:13:50 IST" name="launchApplication" finished-at="2023-05-20T20:13:55 IST" duration-ms="5654" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:SeleniumFrameworkDesign.tests.SubmitOrderTest@294a6b8e]" started-at="2023-05-20T20:13:55 IST" name="submitOrder" data-provider="getData" finished-at="2023-05-20T20:14:09 IST" duration-ms="13894" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{prodtwo=ZARA COAT 3, password=R@hul123, email=rahul.bwn05@gmail.com}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at SeleniumFrameworkDesign.tests.SubmitOrderTest.submitOrder(SubmitOrderTest.java:63)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:SeleniumFrameworkDesign.tests.SubmitOrderTest@294a6b8e]" started-at="2023-05-20T20:14:10 IST" name="tearDown" finished-at="2023-05-20T20:14:10 IST" duration-ms="151" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:SeleniumFrameworkDesign.tests.SubmitOrderTest@294a6b8e]" started-at="2023-05-20T20:14:10 IST" name="launchApplication" finished-at="2023-05-20T20:14:12 IST" duration-ms="2190" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:SeleniumFrameworkDesign.tests.SubmitOrderTest@294a6b8e]" started-at="2023-05-20T20:14:12 IST" name="submitOrder" data-provider="getData" finished-at="2023-05-20T20:14:27 IST" duration-ms="15378" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{prodtwo=IPHONE 13 PRO, password=Umamathur@1234, email=uma_mathur01@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:SeleniumFrameworkDesign.tests.SubmitOrderTest@294a6b8e]" started-at="2023-05-20T20:14:27 IST" name="tearDown" finished-at="2023-05-20T20:14:27 IST" duration-ms="129" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method signature="OrderHistoryTest()[pri:0, instance:SeleniumFrameworkDesign.tests.SubmitOrderTest@294a6b8e]" started-at="2023-05-20T20:14:27 IST" name="OrderHistoryTest" finished-at="2023-05-20T20:14:27 IST" depends-on-methods="SeleniumFrameworkDesign.tests.SubmitOrderTest.submitOrder" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method SeleniumFrameworkDesign.tests.SubmitOrderTest.OrderHistoryTest() on instance SeleniumFrameworkDesign.tests.SubmitOrderTest@294a6b8e depends on not successfully finished methods 
[SeleniumFrameworkDesign.tests.SubmitOrderTest.submitOrder() on instance SeleniumFrameworkDesign.tests.SubmitOrderTest@294a6b8e]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method SeleniumFrameworkDesign.tests.SubmitOrderTest.OrderHistoryTest() on instance SeleniumFrameworkDesign.tests.SubmitOrderTest@294a6b8e depends on not successfully finished methods 
[SeleniumFrameworkDesign.tests.SubmitOrderTest.submitOrder() on instance SeleniumFrameworkDesign.tests.SubmitOrderTest@294a6b8e]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:150)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OrderHistoryTest -->
      </class> <!-- SeleniumFrameworkDesign.tests.SubmitOrderTest -->
    </test> <!-- Submit Order Test -->
  </suite> <!-- Suite -->
</testng-results>
